config/routes.rb
Rails.application.routes.draw do
  resources :buckets

  root 'welcome#index'

end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  acts_as_tree order: "name"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show, :edit, :update, :destroy]

  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.where(parent_id: nil)
  end

  # GET /buckets/1
  # GET /buckets/1.json
  def show
  end

  # GET /buckets/new
  def new
    @bucket = Bucket.new
  end

  # GET /buckets/1/edit
  def edit
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(bucket_params)

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
        format.json { render :show, status: :created, location: @bucket }
      else
        format.html { render :new }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buckets/1
  # PATCH/PUT /buckets/1.json
  def update
    respond_to do |format|
      if @bucket.update(bucket_params)
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bucket }
      else
        format.html { render :edit }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket.destroy
    respond_to do |format|
      format.html { redirect_to buckets_url, notice: 'Bucket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bucket
      @bucket = Bucket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bucket_params
      params[:bucket].permit(:name, :parent_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
  def bucket_breadcrumbs(bucket = nil)
    if bucket.nil?
      content_tag :div, class: "ui breadcrumb segment" do
        concat link_to "Root", buckets_path, class: 'section'
        concat content_tag :i, '', class: 'right chevron icon divider'
      end
    else
      content_tag :div, class: "ui breadcrumb segment" do
        concat link_to "Root", buckets_path
        concat content_tag :i, '', class: 'right chevron icon divider'
        bucket.ancestors.reverse.each do |ancestor|
          concat link_to ancestor.name, bucket_path(ancestor), class: 'section'
          concat content_tag :i, '', class: 'right chevron icon divider'
        end
        concat link_to bucket.name, bucket_path(bucket), class: 'section active'
      end
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buckets/_bucket.html.slim
tr
  td.collapsing
    i.folder.icon.violet
    = link_to bucket.name, bucket
  td 
    = bucket.created_at
    i
      |   (
      = time_ago_in_words(bucket.created_at)
      |  ago )
  td
    .ui.icon.buttons
      = link_to edit_bucket_path(bucket), class: 'ui button blue' do
        i.icon.edit.white
      = link_to bucket, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'ui button red' do
        i.icon.ban.white

app/views/buckets/_form.html.slim
= form_for @bucket, html: {class: 'ui form segment'} do |f|
  - if @bucket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bucket.errors.count, "error")} prohibited this bucket from being saved:"
      ul
        - @bucket.errors.full_messages.each do |message|
          li = message

  .field
    = label_tag :parent_id
    = f.select :parent_id, Bucket.all.map {|x| [x.name, x.id]}, {include_blank: "Root", selected: params[:parent_id]}, {class: 'ui search dropdown'}
  .field
    = label_tag :name
    = f.text_field :name
  .actions
    = f.submit class: 'ui button'

app/views/buckets/edit.html.slim
h1 Editing bucket

== render 'form'

= link_to 'Show', @bucket
'|
= link_to 'Back', buckets_path

app/views/buckets/index.html.slim
.ui.stackable.one.column.grid.page
  .column
    = bucket_breadcrumbs
      i.right.chevron.icon.divider
    table.ui.celled.striped.table
      thead
        tr
          th colspan="3"
            | Root Bucket

      tbody
        = render @buckets
      tfoot.full-width
        tr
          th
          th colspan='4'
            = link_to new_bucket_path, class: 'ui icon labeled button' do
              i.icon.folder
              | New
            

app/views/buckets/new.html.slim
.ui.stackable.one.column.grid.page
  .column
    h1 New bucket

    == render 'form'

    = link_to 'Back', buckets_path

app/views/buckets/show.html.slim
.ui.stackable.one.column.grid.page
  .column
    = bucket_breadcrumbs(@bucket)
    table.ui.celled.striped.table
      thead
        tr
          th colspan="4"
            | #{@bucket.name} Bucket
      tbody
        - @bucket.children.each do |child|
          = render child
      tfoot.full-width
        tr
          th
          th colspan='4'
            = link_to new_bucket_path(parent_id: @bucket), class: 'ui icon labeled button' do
              i.icon.folder
              | New
            = link_to edit_bucket_path, class: 'ui icon labeled button' do
              i.icon.pencil
              | Edit

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Bpbfe
    meta charset="utf-8"
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'shared/sidebar'
    .pusher
      .ui.inverted.main.menu.fixed.blue
        #launcher.title.item
          i.content.icon
          b Menu
        .right.menu
          .title.item
            i.question.icon
        .container

      == yield

app/views/shared/_sidebar.html.slim
.ui.left.vertical.labeled.icon.sidebar.menu
  = link_to root_path, class: 'item' do
    i.home.icon
    | Home
  a.item
    i.mail.icon
    | Messages
  a.item
    i.chat.icon
    | Discussions
  = link_to buckets_path, class: 'item' do
    i.disk.outline.icon
    | Files
  a.item
    i.dashboard.icon
    | Stats

app/views/welcome/index.html.slim
#welcome-container
  .ui.two.column.centered.grid
    .column
      .ui.piled.segment
        h1 Barbary Box
        h3 A Local Captive Portal for Friends, Files, and Fun.
  .ui.stackable.three.column.grid.page
    .column
      .ui.segment.blue
        i.disk.outline.icon.massive.blue
        h3.ui.header
          | Share Files
        p Share Files with strangers. Sounds like a good idea? Probably not. Could be Exciting, like Napster never died with all the safety of Kazaa and Limewire.
    .column
      .ui.segment.red
        i.mail.icon.massive.red
        h3.ui.header
          | Secure Messages
        p Send and Receive Secure Messages. Be all like a spy and stuff. 
    .column
      .ui.segment.green
        i.chat.icon.green.massive
        h3.ui.header
          | Discussions
        p Talk in real time to other people on this Barbary Box in an imageboard format. Yea, your very own 4chan. 